"""db_criar_cadastro

Revision ID: 637e9bdddd05
Revises: c3c9ea3a2b8f
Create Date: 2023-08-17 08:52:28.438129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637e9bdddd05'
down_revision = 'c3c9ea3a2b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_model', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=14), nullable=False))

    # ### end Alembic commands ###
